# Generated by Django 5.2.16 on 2026-08-06 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbontransaction',
            name='transaction_type',
            field=models.CharField(choices=[('Issuance', 'Issuance'), ('Transfer', 'Transfer'), ('Recieve', 'Recieve'), ('Verification', 'Verification'), ('Validation', 'Validation'), ('Cancellation', 'Cancellation')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
