# Generated by Django 5.2.16 on 2026-08-13 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_company_alter_user_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.CharField(choices=[('Blue Carbon Project', 'Blue Carbon Project'), ('Buyer Company', 'Buyer Company'), ('Verifier Organization', 'Verifier Organization'), ('IT', 'IT'), ('Credit Transfer', 'Credit Transfer')], max_length=100),
        ),
    ]
