# Generated by Django 6.0.7 on 2026-07-24 02:32

import django_mongodb_backend.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='User_id',
            field=django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False),
        ),
    ]
