# Generated by Django 6.0.7 on 2026-07-25 11:04

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_company_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonTransaction',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('Issuance', 'Issuance'), ('Transfer', 'Transfer'), ('Recieve', 'Recieve'), ('Verification', 'Verification'), ('Validation', 'Validation'), ('Cancellatiobn', 'Cancellation')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ipfs_cid', models.CharField(blank=True, max_length=100, null=True)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
        ),
    ]
