# Generated by Django 6.0.7 on 2026-07-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_carbontransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Government Official', 'Government Official'), ('Company Buyer', 'Company Buyer'), ('NGO Representative', 'NGO Representative')], max_length=100),
        ),
    ]
