# Generated by Django 5.2.16 on 2026-09-28 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_company_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Primary official contact email', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='credential_document',
            field=models.CharField(blank=True, help_text='Link or URL to credential document / charter', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='estimated_budget',
            field=models.CharField(blank=True, help_text='AI-estimated restoration & audit budget', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='objectives',
            field=models.TextField(blank=True, help_text='AI-extracted quantifiable conservation & MRV objectives', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='project_scope',
            field=models.TextField(blank=True, help_text='AI-extracted project scope and ecosystem rationale', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='registration_number',
            field=models.CharField(blank=True, help_text='Official registration / tax / NGO identifier', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection if application is rejected', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_companies', to='api.user'),
        ),
        migrations.AddField(
            model_name='company',
            name='target_demographics',
            field=models.TextField(blank=True, help_text='AI-identified local community stakeholders', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='domain_expertise',
            field=models.CharField(blank=True, help_text='Field specializations, e.g. Mangrove Forests, Wetland Biomass, Soil Carbon', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, help_text='Operating region or territory', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Government Official', 'Government Official'), ('Company Buyer', 'Company Buyer'), ('NGO Representative', 'NGO Representative'), ('Verifier', 'Field Verifier')], max_length=100),
        ),
        migrations.CreateModel(
            name='VerificationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('Normal', 'Normal'), ('High', 'High'), ('Urgent', 'Urgent')], default='Normal', max_length=20)),
                ('status', models.CharField(choices=[('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Needs Revision', 'Needs Revision')], default='Assigned', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Government official instructions or focus areas', null=True)),
                ('field_report', models.TextField(blank=True, help_text='Verifier findings and audit notes', null=True)),
                ('evidence_document', models.CharField(blank=True, help_text='MRV audit document or IPFS hash', max_length=500, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegated_verifications', to='api.user')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_tasks', to='api.company')),
                ('verifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_verifications', to='api.user')),
            ],
            options={
                'ordering': ['-assigned_date'],
            },
        ),
    ]
