# Generated by Django 6.0.7 on 2026-07-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_company_wallet_address_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbontransaction',
            name='tx_hash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carbontransaction',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
