# Generated by Django 5.2.17 on 2026-09-29 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_company_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='assigned_verifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_projects', to='api.user'),
        ),
        migrations.AddField(
            model_name='company',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='verifier_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
