# Generated by Django 5.2.17 on 2026-09-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_add_verifier_assignment_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Under Review', 'Under Review'), ('Correction Required', 'Correction Required'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=30),
        ),
    ]
