# Generated by Django 5.2.17 on 2026-10-01 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_company_contact_email_company_contact_phone_and_more'),
        ('api', '0010_add_workflow_status_choices'),
    ]

    operations = [
    ]
